---
title: "tidy_data"
author: "Joe LaRocca"
date: "2024-09-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(haven)
```

## Upload Pulse Data

```{r}

pulse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names()

head(pulse_df)

```

## Going from Wide to Long Format

```{r}

pulse_tidy_df =
  pulse_df %>%
  pivot_longer(
    cols = bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    values_to = "bdi_score", #creates new column
    names_prefix = "bdi_score_" #removes prefixes
  ) %>%
  mutate(
    visit = replace(visit, visit == "bl", "00m") #replace "bl" with something easier to read
  ) %>%
  select(id, visit, everything()) #reorganizes the columns

head(pulse_tidy_df)

```

## One More Example: Practice with Litters

```{r}

litters_df =
  read_csv("./data/FAS_litters.csv", na = c("NA", ".", "")) %>%
  janitor::clean_names() %>%
  pivot_longer(
    cols = gd0_weight:gd18_weight,
    names_to = "gd_time",
    values_to = "gestational_weight"
  ) %>% 
  mutate(
    gd_time = replace(gd_time, gd_time == "gd0_weight", 0),
    gd_time = replace(gd_time, gd_time == "gd18_weight", 18)
  )

head(litters_df)

```
### Trying the case_match() function within mutate() -- same result

```{r}

litters_df =
  read_csv("./data/FAS_litters.csv", na = c("NA", ".", "")) %>%
  janitor::clean_names() %>%
  pivot_longer(
    cols = gd0_weight:gd18_weight,
    names_to = "gd_time",
    values_to = "gd_weight"
  ) %>% 
  mutate(
    gd_time = case_match(
      gd_time,
      "gd0_weight" ~ 0,
      "gd18_weight" ~ 18
    )
  )

head(litters_df)

```
## Using Pivot Wider

```{r}

analysis_df =
  tibble(
    group = c("treatment", "treatment", "control", "control"),
    time = c("pre", "post", "pre", "post"),
    mean = c(4, 10, 4.2, 5)
  )

analysis_df

```

### Pivot wider for human readability

```{r}

analysis_df_wide =
  analysis_df %>%
  pivot_wider(
    names_from = time,
    values_from = mean
  ) %>%
  knitr::kable() #easier viewing
  

```
## LOTR Data

### Step 1: Bind the tables

```{r}

fellowship_ring = 
  read_excel("data/LotR_Words.xlsx", range = "B3:D6") %>%
  mutate(movie = "fellowship_ring") #adds a column

two_towers = 
  read_excel("data/LotR_Words.xlsx", range = "F3:H6") %>%
  mutate(movie = "two_towers") 

return_king = 
  read_excel("data/LotR_Words.xlsx", range = "J3:L6") %>%
  mutate(movie = "return_king") 

lotr_df = 
  bind_rows(fellowship_ring,
            two_towers,
            return_king) %>%
  janitor::clean_names() %>%
  pivot_longer(
    cols = female:male,
    names_to = "sex",
    values_to = "words"
  ) %>%
  select(movie, everything()) %>%
  mutate(race = str_to_lower(race))

lotr_df


```

